// Generated by quicktype from the Anthropic OpenAPI spec.
// Do not edit manually — re-run `just generate` instead.

#![allow(dead_code)]
#![allow(clippy::redundant_field_names)]

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct CreateMessageParams {
    /// Top-level cache control automatically applies a cache_control marker to the last
    /// cacheable block in the request.
    cache_control: Option<CacheControlEphemeral>,

    /// Container identifier for reuse across requests.
    container: Option<String>,

    /// Specifies the geographic region for inference processing. If not specified, the
    /// workspace's `default_inference_geo` is used.
    inference_geo: Option<String>,

    /// The maximum number of tokens to generate before stopping.
    ///
    /// Note that our models may stop _before_ reaching this maximum. This parameter only
    /// specifies the absolute maximum number of tokens to generate.
    ///
    /// Different models have different maximum values for this parameter.  See
    /// [models](https://docs.claude.com/en/docs/models-overview) for details.
    max_tokens: i64,

    /// Input messages.
    ///
    /// Our models are trained to operate on alternating `user` and `assistant` conversational
    /// turns. When creating a new `Message`, you specify the prior conversational turns with the
    /// `messages` parameter, and the model then generates the next `Message` in the
    /// conversation. Consecutive `user` or `assistant` turns in your request will be combined
    /// into a single turn.
    ///
    /// Each input message must be an object with a `role` and `content`. You can specify a
    /// single `user`-role message, or you can include multiple `user` and `assistant` messages.
    ///
    /// If the final message uses the `assistant` role, the response content will continue
    /// immediately from the content in that message. This can be used to constrain part of the
    /// model's response.
    ///
    /// Example with a single `user` message:
    ///
    /// ```json
    /// [{"role": "user", "content": "Hello, Claude"}]
    /// ```
    ///
    /// Example with multiple conversational turns:
    ///
    /// ```json
    /// [
    /// {"role": "user", "content": "Hello there."},
    /// {"role": "assistant", "content": "Hi, I'm Claude. How can I help you?"},
    /// {"role": "user", "content": "Can you explain LLMs in plain English?"},
    /// ]
    /// ```
    ///
    /// Example with a partially-filled response from Claude:
    ///
    /// ```json
    /// [
    /// {"role": "user", "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C)
    /// Sun"},
    /// {"role": "assistant", "content": "The best answer is ("},
    /// ]
    /// ```
    ///
    /// Each input message `content` may be either a single `string` or an array of content
    /// blocks, where each block has a specific `type`. Using a `string` for `content` is
    /// shorthand for an array of one content block of type `"text"`. The following input
    /// messages are equivalent:
    ///
    /// ```json
    /// {"role": "user", "content": "Hello, Claude"}
    /// ```
    ///
    /// ```json
    /// {"role": "user", "content": [{"type": "text", "text": "Hello, Claude"}]}
    /// ```
    ///
    /// See [input examples](https://docs.claude.com/en/api/messages-examples).
    ///
    /// Note that if you want to include a [system
    /// prompt](https://docs.claude.com/en/docs/system-prompts), you can use the top-level
    /// `system` parameter — there is no `"system"` role for input messages in the Messages API.
    ///
    /// There is a limit of 100,000 messages in a single request.
    messages: Vec<InputMessage>,

    /// An object describing metadata about the request.
    metadata: Option<Metadata>,

    model: String,

    /// Configuration options for the model's output, such as the output format.
    output_config: Option<OutputConfig>,

    /// Determines whether to use priority capacity (if available) or standard capacity for this
    /// request.
    ///
    /// Anthropic offers different levels of service for your API requests. See
    /// [service-tiers](https://docs.claude.com/en/api/service-tiers) for details.
    service_tier: Option<ServiceTier>,

    /// Custom text sequences that will cause the model to stop generating.
    ///
    /// Our models will normally stop when they have naturally completed their turn, which will
    /// result in a response `stop_reason` of `"end_turn"`.
    ///
    /// If you want the model to stop generating when it encounters custom strings of text, you
    /// can use the `stop_sequences` parameter. If the model encounters one of the custom
    /// sequences, the response `stop_reason` value will be `"stop_sequence"` and the response
    /// `stop_sequence` value will contain the matched stop sequence.
    stop_sequences: Option<Vec<String>>,

    /// Whether to incrementally stream the response using server-sent events.
    ///
    /// See [streaming](https://docs.claude.com/en/api/messages-streaming) for details.
    stream: Option<bool>,

    /// System prompt.
    ///
    /// A system prompt is a way of providing context and instructions to Claude, such as
    /// specifying a particular goal or role. See our [guide to system
    /// prompts](https://docs.claude.com/en/docs/system-prompts).
    system: Option<System>,

    /// Amount of randomness injected into the response.
    ///
    /// Defaults to `1.0`. Ranges from `0.0` to `1.0`. Use `temperature` closer to `0.0` for
    /// analytical / multiple choice, and closer to `1.0` for creative and generative tasks.
    ///
    /// Note that even with `temperature` of `0.0`, the results will not be fully deterministic.
    temperature: Option<f64>,

    thinking: Option<Thinking>,

    tool_choice: Option<ToolChoice>,

    /// Definitions of tools that the model may use.
    ///
    /// If you include `tools` in your API request, the model may return `tool_use` content
    /// blocks that represent the model's use of those tools. You can then run those tools using
    /// the tool input generated by the model and then optionally return results back to the
    /// model using `tool_result` content blocks.
    ///
    /// There are two types of tools: **client tools** and **server tools**. The behavior
    /// described below applies to client tools. For [server
    /// tools](https://docs.claude.com/en/docs/agents-and-tools/tool-use/overview\#server-tools),
    /// see their individual documentation as each has its own behavior (e.g., the [web search
    /// tool](https://docs.claude.com/en/docs/agents-and-tools/tool-use/web-search-tool)).
    ///
    /// Each tool definition includes:
    ///
    /// * `name`: Name of the tool.
    /// * `description`: Optional, but strongly-recommended description of the tool.
    /// * `input_schema`: [JSON schema](https://json-schema.org/draft/2020-12) for the tool
    /// `input` shape that the model will produce in `tool_use` output content blocks.
    ///
    /// For example, if you defined `tools` as:
    ///
    /// ```json
    /// [
    /// {
    /// "name": "get_stock_price",
    /// "description": "Get the current stock price for a given ticker symbol.",
    /// "input_schema": {
    /// "type": "object",
    /// "properties": {
    /// "ticker": {
    /// "type": "string",
    /// "description": "The stock ticker symbol, e.g. AAPL for Apple Inc."
    /// }
    /// },
    /// "required": ["ticker"]
    /// }
    /// }
    /// ]
    /// ```
    ///
    /// And then asked the model "What's the S&P 500 at today?", the model might produce
    /// `tool_use` content blocks in the response like this:
    ///
    /// ```json
    /// [
    /// {
    /// "type": "tool_use",
    /// "id": "toolu_01D7FLrfh4GYq7yT1ULFeyMV",
    /// "name": "get_stock_price",
    /// "input": { "ticker": "^GSPC" }
    /// }
    /// ]
    /// ```
    ///
    /// You might then run your `get_stock_price` tool with `{"ticker": "^GSPC"}` as an input,
    /// and return the following back to the model in a subsequent `user` message:
    ///
    /// ```json
    /// [
    /// {
    /// "type": "tool_result",
    /// "tool_use_id": "toolu_01D7FLrfh4GYq7yT1ULFeyMV",
    /// "content": "259.75 USD"
    /// }
    /// ]
    /// ```
    ///
    /// Tools can be used for workflows that include running client-side tools and functions, or
    /// more generally whenever you want the model to produce a particular JSON structure of
    /// output.
    ///
    /// See our [guide](https://docs.claude.com/en/docs/tool-use) for more details.
    tools: Option<Vec<Tool>>,

    /// Only sample from the top K options for each subsequent token.
    ///
    /// Used to remove "long tail" low probability responses. [Learn more technical details
    /// here](https://towardsdatascience.com/how-to-sample-from-language-models-682bceb97277).
    ///
    /// Recommended for advanced use cases only. You usually only need to use `temperature`.
    top_k: Option<i64>,

    /// Use nucleus sampling.
    ///
    /// In nucleus sampling, we compute the cumulative distribution over all the options for each
    /// subsequent token in decreasing probability order and cut it off once it reaches a
    /// particular probability specified by `top_p`. You should either alter `temperature` or
    /// `top_p`, but not both.
    ///
    /// Recommended for advanced use cases only. You usually only need to use `temperature`.
    top_p: Option<f64>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct CacheControlEphemeral {
    /// The time-to-live for the cache control breakpoint.
    ///
    /// This may be one the following values:
    /// - `5m`: 5 minutes
    /// - `1h`: 1 hour
    ///
    /// Defaults to `5m`.
    ttl: Option<Ttl>,

    #[serde(rename = "type")]
    cache_control_ephemeral_type: CacheControlEphemeralType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum CacheControlEphemeralType {
    Ephemeral,
}

/// The time-to-live for the cache control breakpoint.
///
/// This may be one the following values:
/// - `5m`: 5 minutes
/// - `1h`: 1 hour
///
/// Defaults to `5m`.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub enum Ttl {
    #[serde(rename = "1h")]
    The1H,

    #[serde(rename = "5m")]
    The5M,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct InputMessage {
    content: MessageContent,

    role: Role,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum MessageContent {
    InputContentBlockArray(Vec<InputContentBlock>),

    String(String),
}

/// Regular text content.
///
/// Image content specified directly as base64 data or as a reference via a URL.
///
/// Document content, either specified directly as base64 data, as text, or as a reference
/// via a URL.
///
/// A search result block containing source, title, and content from search operations.
///
/// A block specifying internal thinking by the model.
///
/// A block specifying internal, redacted thinking by the model.
///
/// A block indicating a tool use by the model.
///
/// A block specifying the results of a tool use by the model.
///
/// A content block that represents a file to be uploaded to the container
/// Files uploaded via this block will be available in the container's input directory.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct InputContentBlock {
    /// Create a cache control breakpoint at this content block.
    cache_control: Option<CacheControlEphemeral>,

    citations: Option<Citations>,

    text: Option<String>,

    #[serde(rename = "type")]
    input_content_block_type: InputContentBlockType,

    source: Option<Source>,

    context: Option<String>,

    title: Option<String>,

    content: Option<Content>,

    signature: Option<String>,

    thinking: Option<String>,

    data: Option<String>,

    caller: Option<Caller>,

    id: Option<String>,

    #[schema(value_type = Option<Object>)]
    input: Option<HashMap<String, Option<serde_json::Value>>>,

    name: Option<String>,

    is_error: Option<bool>,

    tool_use_id: Option<String>,

    file_id: Option<String>,
}

/// Tool invocation directly from the model.
///
/// Tool invocation generated by a server-side tool.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct Caller {
    #[serde(rename = "type")]
    caller_type: AllowedCaller,

    tool_id: Option<String>,
}

/// Specifies who can invoke a tool.
///
/// Values:
/// direct: The model can call this tool directly.
/// code_execution_20250825: The tool can be called from the code execution environment
/// (v1).
/// code_execution_20260120: The tool can be called from the code execution environment (v2
/// with persistence).
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum AllowedCaller {
    #[serde(rename = "code_execution_20250825")]
    CodeExecution20250825,

    #[serde(rename = "code_execution_20260120")]
    CodeExecution20260120,

    Direct,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum Citations {
    RequestCitationsConfig(RequestCitationsConfig),

    RequestLocationCitationArray(Vec<RequestLocationCitation>),
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestLocationCitation {
    cited_text: String,

    document_index: Option<i64>,

    document_title: Option<String>,

    end_char_index: Option<i64>,

    start_char_index: Option<i64>,

    #[serde(rename = "type")]
    request_location_citation_type: CitationType,

    end_page_number: Option<i64>,

    start_page_number: Option<i64>,

    end_block_index: Option<i64>,

    start_block_index: Option<i64>,

    encrypted_index: Option<String>,

    title: Option<String>,

    url: Option<String>,

    search_result_index: Option<i64>,

    source: Option<String>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum CitationType {
    #[serde(rename = "char_location")]
    CharLocation,

    #[serde(rename = "content_block_location")]
    ContentBlockLocation,

    #[serde(rename = "page_location")]
    PageLocation,

    #[serde(rename = "search_result_location")]
    SearchResultLocation,

    #[serde(rename = "web_search_result_location")]
    WebSearchResultLocation,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestCitationsConfig {
    enabled: Option<bool>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum Content {
    BlockArray(Vec<Block>),

    RequestWebSearchToolResultError(RequestWebSearchToolResultError),

    String(String),
}

/// Regular text content.
///
/// Image content specified directly as base64 data or as a reference via a URL.
///
/// A search result block containing source, title, and content from search operations.
///
/// Document content, either specified directly as base64 data, as text, or as a reference
/// via a URL.
///
/// Tool reference block that can be included in tool_result content.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct Block {
    /// Create a cache control breakpoint at this content block.
    cache_control: Option<CacheControlEphemeral>,

    citations: Option<Citations>,

    text: Option<String>,

    #[serde(rename = "type")]
    block_type: WebSearchToolResultBlockItemType,

    source: Option<Source>,

    content: Option<Vec<RequestTextBlock>>,

    title: Option<String>,

    context: Option<String>,

    tool_name: Option<String>,

    encrypted_content: Option<String>,

    page_age: Option<String>,

    url: Option<String>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum WebSearchToolResultBlockItemType {
    Document,

    Image,

    #[serde(rename = "search_result")]
    SearchResult,

    Text,

    #[serde(rename = "tool_reference")]
    ToolReference,

    #[serde(rename = "web_search_result")]
    WebSearchResult,
}

/// Regular text content.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestTextBlock {
    /// Create a cache control breakpoint at this content block.
    cache_control: Option<CacheControlEphemeral>,

    citations: Option<Vec<RequestLocationCitation>>,

    text: String,

    #[serde(rename = "type")]
    request_text_block_type: SystemType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum SystemType {
    Text,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum Source {
    SourceSource(SourceSource),

    String(String),
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct SourceSource {
    data: Option<String>,

    media_type: Option<FluffyMediaType>,

    #[serde(rename = "type")]
    source_type: FluffyType,

    url: Option<String>,

    content: Option<SourceContent>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum SourceContent {
    ContentBlockSourceContentItemArray(Vec<ContentBlockSourceContentItem>),

    String(String),
}

/// Regular text content.
///
/// Image content specified directly as base64 data or as a reference via a URL.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ContentBlockSourceContentItem {
    /// Create a cache control breakpoint at this content block.
    cache_control: Option<CacheControlEphemeral>,

    citations: Option<Vec<RequestLocationCitation>>,

    text: Option<String>,

    #[serde(rename = "type")]
    content_block_source_content_item_type: ContentBlockSourceContentItemType,

    source: Option<SourceSourceClass>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ContentBlockSourceContentItemType {
    Image,

    Text,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct SourceSourceClass {
    data: Option<String>,

    media_type: Option<PurpleMediaType>,

    #[serde(rename = "type")]
    source_type: PurpleType,

    url: Option<String>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub enum PurpleMediaType {
    #[serde(rename = "image/gif")]
    ImageGif,

    #[serde(rename = "image/jpeg")]
    ImageJpeg,

    #[serde(rename = "image/png")]
    ImagePng,

    #[serde(rename = "image/webp")]
    ImageWebp,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum PurpleType {
    Base64,

    Url,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub enum FluffyMediaType {
    #[serde(rename = "application/pdf")]
    ApplicationPdf,

    #[serde(rename = "image/gif")]
    ImageGif,

    #[serde(rename = "image/jpeg")]
    ImageJpeg,

    #[serde(rename = "image/png")]
    ImagePng,

    #[serde(rename = "image/webp")]
    ImageWebp,

    #[serde(rename = "text/plain")]
    TextPlain,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum FluffyType {
    Base64,

    Content,

    Text,

    Url,
}

/// Code execution result with encrypted stdout for PFC + web_search results.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestWebSearchToolResultError {
    error_code: Option<ToolResultErrorCode>,

    #[serde(rename = "type")]
    request_web_search_tool_result_error_type: RequestWebSearchToolResultErrorType,

    content: Option<RequestWebSearchToolResultErrorContent>,

    /// ISO 8601 timestamp when the content was retrieved
    retrieved_at: Option<String>,

    /// Fetched content URL
    url: Option<String>,

    return_code: Option<i64>,

    stderr: Option<String>,

    stdout: Option<String>,

    encrypted_stdout: Option<String>,

    error_message: Option<String>,

    file_type: Option<FileType>,

    num_lines: Option<i64>,

    start_line: Option<i64>,

    total_lines: Option<i64>,

    is_file_update: Option<bool>,

    lines: Option<Vec<String>>,

    new_lines: Option<i64>,

    new_start: Option<i64>,

    old_lines: Option<i64>,

    old_start: Option<i64>,

    tool_references: Option<Vec<RequestToolReferenceBlock>>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum RequestWebSearchToolResultErrorContent {
    RequestCodeExecutionOutputBlockArray(Vec<RequestCodeExecutionOutputBlock>),

    RequestDocumentBlock(RequestDocumentBlock),

    String(String),
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestCodeExecutionOutputBlock {
    file_id: String,

    #[serde(rename = "type")]
    request_code_execution_output_block_type: TentacledType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum TentacledType {
    #[serde(rename = "bash_code_execution_output")]
    BashCodeExecutionOutput,

    #[serde(rename = "code_execution_output")]
    CodeExecutionOutput,
}

/// Document content, either specified directly as base64 data, as text, or as a reference
/// via a URL.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestDocumentBlock {
    /// Create a cache control breakpoint at this content block.
    cache_control: Option<CacheControlEphemeral>,

    citations: Option<RequestCitationsConfig>,

    context: Option<String>,

    source: ContentSource,

    title: Option<String>,

    #[serde(rename = "type")]
    request_document_block_type: StickyType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum StickyType {
    Document,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ContentSource {
    data: Option<String>,

    media_type: Option<TentacledMediaType>,

    #[serde(rename = "type")]
    source_type: FluffyType,

    content: Option<SourceContent>,

    url: Option<String>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub enum TentacledMediaType {
    #[serde(rename = "application/pdf")]
    ApplicationPdf,

    #[serde(rename = "text/plain")]
    TextPlain,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ToolResultErrorCode {
    #[serde(rename = "execution_time_exceeded")]
    ExecutionTimeExceeded,

    #[serde(rename = "file_not_found")]
    FileNotFound,

    #[serde(rename = "invalid_tool_input")]
    InvalidToolInput,

    #[serde(rename = "max_uses_exceeded")]
    MaxUsesExceeded,

    #[serde(rename = "output_file_too_large")]
    OutputFileTooLarge,

    #[serde(rename = "query_too_long")]
    QueryTooLong,

    #[serde(rename = "request_too_large")]
    RequestTooLarge,

    #[serde(rename = "too_many_requests")]
    TooManyRequests,

    Unavailable,

    #[serde(rename = "unsupported_content_type")]
    UnsupportedContentType,

    #[serde(rename = "url_not_accessible")]
    UrlNotAccessible,

    #[serde(rename = "url_not_allowed")]
    UrlNotAllowed,

    #[serde(rename = "url_too_long")]
    UrlTooLong,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum FileType {
    Image,

    Pdf,

    Text,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum RequestWebSearchToolResultErrorType {
    #[serde(rename = "bash_code_execution_result")]
    BashCodeExecutionResult,

    #[serde(rename = "bash_code_execution_tool_result_error")]
    BashCodeExecutionToolResultError,

    #[serde(rename = "code_execution_result")]
    CodeExecutionResult,

    #[serde(rename = "code_execution_tool_result_error")]
    CodeExecutionToolResultError,

    #[serde(rename = "encrypted_code_execution_result")]
    EncryptedCodeExecutionResult,

    #[serde(rename = "text_editor_code_execution_create_result")]
    TextEditorCodeExecutionCreateResult,

    #[serde(rename = "text_editor_code_execution_str_replace_result")]
    TextEditorCodeExecutionStrReplaceResult,

    #[serde(rename = "text_editor_code_execution_tool_result_error")]
    TextEditorCodeExecutionToolResultError,

    #[serde(rename = "text_editor_code_execution_view_result")]
    TextEditorCodeExecutionViewResult,

    #[serde(rename = "tool_search_tool_result_error")]
    ToolSearchToolResultError,

    #[serde(rename = "tool_search_tool_search_result")]
    ToolSearchToolSearchResult,

    #[serde(rename = "web_fetch_result")]
    WebFetchResult,

    #[serde(rename = "web_fetch_tool_result_error")]
    WebFetchToolResultError,

    #[serde(rename = "web_search_tool_result_error")]
    WebSearchToolResultError,
}

/// Tool reference block that can be included in tool_result content.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestToolReferenceBlock {
    /// Create a cache control breakpoint at this content block.
    cache_control: Option<CacheControlEphemeral>,

    tool_name: String,

    #[serde(rename = "type")]
    request_tool_reference_block_type: ToolReferenceType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ToolReferenceType {
    #[serde(rename = "tool_reference")]
    ToolReference,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum InputContentBlockType {
    #[serde(rename = "bash_code_execution_tool_result")]
    BashCodeExecutionToolResult,

    #[serde(rename = "code_execution_tool_result")]
    CodeExecutionToolResult,

    #[serde(rename = "container_upload")]
    ContainerUpload,

    Document,

    Image,

    #[serde(rename = "redacted_thinking")]
    RedactedThinking,

    #[serde(rename = "search_result")]
    SearchResult,

    #[serde(rename = "server_tool_use")]
    ServerToolUse,

    Text,

    #[serde(rename = "text_editor_code_execution_tool_result")]
    TextEditorCodeExecutionToolResult,

    Thinking,

    #[serde(rename = "tool_result")]
    ToolResult,

    #[serde(rename = "tool_search_tool_result")]
    ToolSearchToolResult,

    #[serde(rename = "tool_use")]
    ToolUse,

    #[serde(rename = "web_fetch_tool_result")]
    WebFetchToolResult,

    #[serde(rename = "web_search_tool_result")]
    WebSearchToolResult,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum Role {
    Assistant,

    User,
}

/// An object describing metadata about the request.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct Metadata {
    /// An external identifier for the user who is associated with the request.
    ///
    /// This should be a uuid, hash value, or other opaque identifier. Anthropic may use this id
    /// to help detect abuse. Do not include any identifying information such as name, email
    /// address, or phone number.
    user_id: Option<String>,
}

/// Configuration options for the model's output, such as the output format.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct OutputConfig {
    /// How much effort the model should put into its response. Higher effort levels may result
    /// in more thorough analysis but take longer.
    ///
    /// Valid values are `low`, `medium`, `high`, or `max`.
    effort: Option<EffortLevel>,

    /// A schema to specify Claude's output format in responses. See [structured
    /// outputs](https://platform.claude.com/docs/en/build-with-claude/structured-outputs)
    format: Option<JsonOutputFormat>,
}

/// All possible effort levels.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum EffortLevel {
    High,

    Low,

    Max,

    Medium,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct JsonOutputFormat {
    /// The JSON schema of the format
    #[schema(value_type = Object)]
    schema: HashMap<String, Option<serde_json::Value>>,

    #[serde(rename = "type")]
    json_output_format_type: JsonOutputFormatType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum JsonOutputFormatType {
    #[serde(rename = "json_schema")]
    JsonSchema,
}

/// Determines whether to use priority capacity (if available) or standard capacity for this
/// request.
///
/// Anthropic offers different levels of service for your API requests. See
/// [service-tiers](https://docs.claude.com/en/api/service-tiers) for details.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ServiceTier {
    Auto,

    #[serde(rename = "standard_only")]
    StandardOnly,
}

/// System prompt.
///
/// A system prompt is a way of providing context and instructions to Claude, such as
/// specifying a particular goal or role. See our [guide to system
/// prompts](https://docs.claude.com/en/docs/system-prompts).
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum System {
    RequestTextBlockArray(Vec<RequestTextBlock>),

    String(String),
}

/// Configuration for enabling Claude's extended thinking.
///
/// When enabled, responses include `thinking` content blocks showing Claude's thinking
/// process before the final answer. Requires a minimum budget of 1,024 tokens and counts
/// towards your `max_tokens` limit.
///
/// See [extended
/// thinking](https://docs.claude.com/en/docs/build-with-claude/extended-thinking) for
/// details.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct Thinking {
    /// Determines how many tokens Claude can use for its internal reasoning process. Larger
    /// budgets can enable more thorough analysis for complex problems, improving response
    /// quality.
    ///
    /// Must be ≥1024 and less than `max_tokens`.
    ///
    /// See [extended
    /// thinking](https://docs.claude.com/en/docs/build-with-claude/extended-thinking) for
    /// details.
    budget_tokens: Option<i64>,

    /// Controls how thinking content appears in the response. When set to `summarized`, thinking
    /// is returned normally. When set to `omitted`, thinking content is redacted but a signature
    /// is returned for multi-turn continuity. Defaults to `summarized`.
    display: Option<ThinkingDisplayMode>,

    #[serde(rename = "type")]
    thinking_type: ThinkingType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ThinkingDisplayMode {
    Omitted,

    Summarized,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ThinkingType {
    Adaptive,

    Disabled,

    Enabled,
}

/// How the model should use the provided tools. The model can use a specific tool, any
/// available tool, decide by itself, or not use tools at all.
///
/// The model will automatically decide whether to use tools.
///
/// The model will use any available tools.
///
/// The model will use the specified tool with `tool_choice.name`.
///
/// The model will not be allowed to use tools.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ToolChoice {
    /// Whether to disable parallel tool use.
    ///
    /// Defaults to `false`. If set to `true`, the model will output at most one tool use.
    ///
    /// Whether to disable parallel tool use.
    ///
    /// Defaults to `false`. If set to `true`, the model will output exactly one tool use.
    disable_parallel_tool_use: Option<bool>,

    #[serde(rename = "type")]
    tool_choice_type: ToolChoiceType,

    /// The name of the tool to use.
    name: Option<String>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ToolChoiceType {
    Any,

    Auto,

    None,

    Tool,
}

/// Code execution tool with REPL state persistence (daemon mode + gVisor checkpoint).
///
/// Web fetch tool with use_cache parameter for bypassing cached content.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct Tool {
    allowed_callers: Option<Vec<AllowedCaller>>,

    /// Create a cache control breakpoint at this content block.
    cache_control: Option<CacheControlEphemeral>,

    /// If true, tool will not be included in initial system prompt. Only loaded when returned
    /// via tool_reference from tool search.
    defer_loading: Option<bool>,

    /// Description of what this tool does.
    ///
    /// Tool descriptions should be as detailed as possible. The more information that the model
    /// has about what the tool is and how to use it, the better it will perform. You can use
    /// natural language descriptions to reinforce important aspects of the tool input JSON
    /// schema.
    description: Option<String>,

    /// Enable eager input streaming for this tool. When true, tool input parameters will be
    /// streamed incrementally as they are generated, and types will be inferred on-the-fly
    /// rather than buffering the full JSON output. When false, streaming is disabled for this
    /// tool even if the fine-grained-tool-streaming beta is active. When null (default), uses
    /// the default behavior based on beta headers.
    eager_input_streaming: Option<bool>,

    #[schema(value_type = Option<Vec<Object>>)]
    input_examples: Option<Vec<HashMap<String, Option<serde_json::Value>>>>,

    /// [JSON schema](https://json-schema.org/draft/2020-12) for this tool's input.
    ///
    /// This defines the shape of the `input` that your tool accepts and that the model will
    /// produce.
    input_schema: Option<InputSchema>,

    /// Name of the tool.
    ///
    /// This is how the tool will be called by the model and in `tool_use` blocks.
    name: String,

    /// When true, guarantees schema validation on tool names and inputs
    strict: Option<bool>,

    #[serde(rename = "type")]
    tool_type: Option<ToolType>,

    /// Maximum number of characters to display when viewing a file. If not specified, defaults
    /// to displaying the full file.
    max_characters: Option<i64>,

    /// If provided, only these domains will be included in results. Cannot be used alongside
    /// `blocked_domains`.
    ///
    /// List of domains to allow fetching from
    allowed_domains: Option<Vec<String>>,

    /// If provided, these domains will never appear in results. Cannot be used alongside
    /// `allowed_domains`.
    ///
    /// List of domains to block fetching from
    blocked_domains: Option<Vec<String>>,

    /// Maximum number of times the tool can be used in the API request.
    max_uses: Option<i64>,

    /// Parameters for the user's location. Used to provide more relevant search results.
    user_location: Option<UserLocation>,

    /// Citations configuration for fetched documents. Citations are disabled by default.
    citations: Option<RequestCitationsConfig>,

    /// Maximum number of tokens used by including web page text content in the context. The
    /// limit is approximate and does not apply to binary content such as PDFs.
    max_content_tokens: Option<i64>,

    /// Whether to use cached content. Set to false to bypass the cache and fetch fresh content.
    /// Only set to false when the user explicitly requests fresh content or when fetching
    /// rapidly-changing sources.
    use_cache: Option<bool>,
}

/// [JSON schema](https://json-schema.org/draft/2020-12) for this tool's input.
///
/// This defines the shape of the `input` that your tool accepts and that the model will
/// produce.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct InputSchema {
    #[schema(value_type = Option<Object>)]
    properties: Option<HashMap<String, Option<serde_json::Value>>>,

    required: Option<Vec<String>>,

    #[serde(rename = "type")]
    input_schema_type: InputSchemaType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum InputSchemaType {
    Object,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ToolType {
    #[serde(rename = "bash_20250124")]
    Bash20250124,

    #[serde(rename = "code_execution_20250522")]
    CodeExecution20250522,

    #[serde(rename = "code_execution_20250825")]
    CodeExecution20250825,

    #[serde(rename = "code_execution_20260120")]
    CodeExecution20260120,

    Custom,

    #[serde(rename = "memory_20250818")]
    Memory20250818,

    #[serde(rename = "text_editor_20250124")]
    TextEditor20250124,

    #[serde(rename = "text_editor_20250429")]
    TextEditor20250429,

    #[serde(rename = "text_editor_20250728")]
    TextEditor20250728,

    #[serde(rename = "tool_search_tool_bm25")]
    ToolSearchToolBm25,

    #[serde(rename = "tool_search_tool_bm25_20251119")]
    ToolSearchToolBm2520251119,

    #[serde(rename = "tool_search_tool_regex")]
    ToolSearchToolRegex,

    #[serde(rename = "tool_search_tool_regex_20251119")]
    ToolSearchToolRegex20251119,

    #[serde(rename = "web_fetch_20250910")]
    WebFetch20250910,

    #[serde(rename = "web_fetch_20260209")]
    WebFetch20260209,

    #[serde(rename = "web_fetch_20260309")]
    WebFetch20260309,

    #[serde(rename = "web_search_20250305")]
    WebSearch20250305,

    #[serde(rename = "web_search_20260209")]
    WebSearch20260209,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct UserLocation {
    /// The city of the user.
    city: Option<String>,

    /// The two letter [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of
    /// the user.
    country: Option<String>,

    /// The region of the user.
    region: Option<String>,

    /// The [IANA timezone](https://nodatime.org/TimeZones) of the user.
    timezone: Option<String>,

    #[serde(rename = "type")]
    user_location_type: UserLocationType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum UserLocationType {
    Approximate,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct Message {
    /// Information about the container used in this request.
    ///
    /// This will be non-null if a container tool (e.g. code execution) was used.
    container: Option<Container>,

    /// Content generated by the model.
    ///
    /// This is an array of content blocks, each of which has a `type` that determines its
    /// shape.
    ///
    /// Example:
    ///
    /// ```json
    /// [{"type": "text", "text": "Hi, I'm Claude."}]
    /// ```
    ///
    /// If the request input `messages` ended with an `assistant` turn, then the response
    /// `content` will continue directly from that last turn. You can use this to constrain the
    /// model's output.
    ///
    /// For example, if the input `messages` were:
    /// ```json
    /// [
    /// {"role": "user", "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C)
    /// Sun"},
    /// {"role": "assistant", "content": "The best answer is ("}
    /// ]
    /// ```
    ///
    /// Then the response `content` might be:
    ///
    /// ```json
    /// [{"type": "text", "text": "B)"}]
    /// ```
    content: Vec<ContentBlock>,

    /// Unique object identifier.
    ///
    /// The format and length of IDs may change over time.
    id: String,

    model: String,

    /// Conversational role of the generated message.
    ///
    /// This will always be `"assistant"`.
    role: Role,

    /// Structured information about why model output stopped.
    ///
    /// This is `null` when the `stop_reason` has no additional detail to report.
    stop_details: Option<RefusalStopDetails>,

    /// The reason that we stopped.
    ///
    /// This may be one the following values:
    /// * `"end_turn"`: the model reached a natural stopping point
    /// * `"max_tokens"`: we exceeded the requested `max_tokens` or the model's maximum
    /// * `"stop_sequence"`: one of your provided custom `stop_sequences` was generated
    /// * `"tool_use"`: the model invoked one or more tools
    /// * `"pause_turn"`: we paused a long-running turn. You may provide the response back as-is
    /// in a subsequent request to let the model continue.
    /// * `"refusal"`: when streaming classifiers intervene to handle potential policy
    /// violations
    ///
    /// In non-streaming mode this value is always non-null. In streaming mode, it is null in the
    /// `message_start` event and non-null otherwise.
    stop_reason: Option<StopReason>,

    /// Which custom stop sequence was generated, if any.
    ///
    /// This value will be a non-null string if one of your custom stop sequences was generated.
    stop_sequence: Option<String>,

    /// Object type.
    ///
    /// For Messages, this is always `"message"`.
    #[serde(rename = "type")]
    message_type: MessageType,

    /// Billing and rate-limit usage.
    ///
    /// Anthropic's API bills and rate-limits by token counts, as tokens represent the underlying
    /// cost to our systems.
    ///
    /// Under the hood, the API transforms requests into a format suitable for the model. The
    /// model's output then goes through a parsing stage before becoming an API response. As a
    /// result, the token counts in `usage` will not match one-to-one with the exact visible
    /// content of an API request or response.
    ///
    /// For example, `output_tokens` will be non-zero, even for an empty string response from
    /// Claude.
    ///
    /// Total input tokens in a request is the summation of `input_tokens`,
    /// `cache_creation_input_tokens`, and `cache_read_input_tokens`.
    usage: Usage,
}

/// Information about the container used in the request (for the code execution tool)
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct Container {
    /// The time at which the container will expire.
    expires_at: String,

    /// Identifier for the container used in this request
    id: String,
}

/// Response model for a file uploaded to the container.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ContentBlock {
    /// Citations supporting the text block.
    ///
    /// The type of citation returned will depend on the type of document being cited. Citing a
    /// PDF results in `page_location`, plain text results in `char_location`, and content
    /// document results in `content_block_location`.
    citations: Option<Vec<ResponseLocationCitation>>,

    text: Option<String>,

    #[serde(rename = "type")]
    content_block_type: ContentBlockType,

    signature: Option<String>,

    thinking: Option<String>,

    data: Option<String>,

    caller: Option<Caller>,

    id: Option<String>,

    #[schema(value_type = Option<Object>)]
    input: Option<HashMap<String, Option<serde_json::Value>>>,

    name: Option<String>,

    content: Option<Content>,

    tool_use_id: Option<String>,

    file_id: Option<String>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum CallerType {
    #[serde(rename = "code_execution_20250825")]
    CodeExecution20250825,

    #[serde(rename = "code_execution_20260120")]
    CodeExecution20260120,

    Direct,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseLocationCitation {
    cited_text: String,

    document_index: Option<i64>,

    document_title: Option<String>,

    end_char_index: Option<i64>,

    file_id: Option<String>,

    start_char_index: Option<i64>,

    #[serde(rename = "type")]
    response_location_citation_type: CitationType,

    end_page_number: Option<i64>,

    start_page_number: Option<i64>,

    end_block_index: Option<i64>,

    start_block_index: Option<i64>,

    encrypted_index: Option<String>,

    title: Option<String>,

    url: Option<String>,

    search_result_index: Option<i64>,

    source: Option<String>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseWebSearchResultBlock {
    encrypted_content: String,

    page_age: Option<String>,

    title: String,

    #[serde(rename = "type")]
    response_web_search_result_block_type: PurpleType,

    url: String,
}

/// Code execution result with encrypted stdout for PFC + web_search results.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseWebSearchToolResultError {
    error_code: Option<ToolResultErrorCode>,

    #[serde(rename = "type")]
    response_web_search_tool_result_error_type: ResponseWebSearchToolResultErrorType,

    content: Option<ResponseWebSearchToolResultErrorContent>,

    /// ISO 8601 timestamp when the content was retrieved
    retrieved_at: Option<String>,

    /// Fetched content URL
    url: Option<String>,

    return_code: Option<i64>,

    stderr: Option<String>,

    stdout: Option<String>,

    encrypted_stdout: Option<String>,

    error_message: Option<String>,

    file_type: Option<FileType>,

    num_lines: Option<i64>,

    start_line: Option<i64>,

    total_lines: Option<i64>,

    is_file_update: Option<bool>,

    lines: Option<Vec<String>>,

    new_lines: Option<i64>,

    new_start: Option<i64>,

    old_lines: Option<i64>,

    old_start: Option<i64>,

    tool_references: Option<Vec<ResponseToolReferenceBlock>>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum ResponseWebSearchToolResultErrorContent {
    ResponseCodeExecutionOutputBlockArray(Vec<ResponseCodeExecutionOutputBlock>),

    ResponseDocumentBlock(ResponseDocumentBlock),

    String(String),
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseCodeExecutionOutputBlock {
    file_id: String,

    #[serde(rename = "type")]
    response_code_execution_output_block_type: FluffyType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseDocumentBlock {
    /// Citation configuration for the document
    citations: Option<ResponseCitationsConfig>,

    source: Source,

    /// The title of the document
    title: Option<String>,

    #[serde(rename = "type")]
    response_document_block_type: TentacledType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseCitationsConfig {
    enabled: bool,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub enum MediaType {
    #[serde(rename = "application/pdf")]
    ApplicationPdf,

    #[serde(rename = "text/plain")]
    TextPlain,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum SourceType {
    Base64,

    Text,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ResponseWebSearchToolResultErrorType {
    #[serde(rename = "bash_code_execution_result")]
    BashCodeExecutionResult,

    #[serde(rename = "bash_code_execution_tool_result_error")]
    BashCodeExecutionToolResultError,

    #[serde(rename = "code_execution_result")]
    CodeExecutionResult,

    #[serde(rename = "code_execution_tool_result_error")]
    CodeExecutionToolResultError,

    #[serde(rename = "encrypted_code_execution_result")]
    EncryptedCodeExecutionResult,

    #[serde(rename = "text_editor_code_execution_create_result")]
    TextEditorCodeExecutionCreateResult,

    #[serde(rename = "text_editor_code_execution_str_replace_result")]
    TextEditorCodeExecutionStrReplaceResult,

    #[serde(rename = "text_editor_code_execution_tool_result_error")]
    TextEditorCodeExecutionToolResultError,

    #[serde(rename = "text_editor_code_execution_view_result")]
    TextEditorCodeExecutionViewResult,

    #[serde(rename = "tool_search_tool_result_error")]
    ToolSearchToolResultError,

    #[serde(rename = "tool_search_tool_search_result")]
    ToolSearchToolSearchResult,

    #[serde(rename = "web_fetch_result")]
    WebFetchResult,

    #[serde(rename = "web_fetch_tool_result_error")]
    WebFetchToolResultError,

    #[serde(rename = "web_search_tool_result_error")]
    WebSearchToolResultError,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseToolReferenceBlock {
    tool_name: String,

    #[serde(rename = "type")]
    response_tool_reference_block_type: ToolReferenceType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ContentBlockType {
    #[serde(rename = "bash_code_execution_tool_result")]
    BashCodeExecutionToolResult,

    #[serde(rename = "code_execution_tool_result")]
    CodeExecutionToolResult,

    #[serde(rename = "container_upload")]
    ContainerUpload,

    #[serde(rename = "redacted_thinking")]
    RedactedThinking,

    #[serde(rename = "server_tool_use")]
    ServerToolUse,

    Text,

    #[serde(rename = "text_editor_code_execution_tool_result")]
    TextEditorCodeExecutionToolResult,

    Thinking,

    #[serde(rename = "tool_search_tool_result")]
    ToolSearchToolResult,

    #[serde(rename = "tool_use")]
    ToolUse,

    #[serde(rename = "web_fetch_tool_result")]
    WebFetchToolResult,

    #[serde(rename = "web_search_tool_result")]
    WebSearchToolResult,
}

/// Object type.
///
/// For Messages, this is always `"message"`.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum MessageType {
    Message,
}

/// Structured information about a refusal.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct RefusalStopDetails {
    /// The policy category that triggered the refusal.
    ///
    /// `null` when the refusal doesn't map to a named category.
    category: Option<Category>,

    /// Human-readable explanation of the refusal.
    ///
    /// This text is not guaranteed to be stable. `null` when no explanation is available for the
    /// category.
    explanation: Option<String>,

    #[serde(rename = "type")]
    refusal_stop_details_type: RefusalStopDetailsType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum Category {
    Bio,

    Cyber,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum RefusalStopDetailsType {
    Refusal,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    #[serde(rename = "end_turn")]
    EndTurn,

    #[serde(rename = "max_tokens")]
    MaxTokens,

    #[serde(rename = "pause_turn")]
    PauseTurn,

    Refusal,

    #[serde(rename = "stop_sequence")]
    StopSequence,

    #[serde(rename = "tool_use")]
    ToolUse,
}

/// Billing and rate-limit usage.
///
/// Anthropic's API bills and rate-limits by token counts, as tokens represent the underlying
/// cost to our systems.
///
/// Under the hood, the API transforms requests into a format suitable for the model. The
/// model's output then goes through a parsing stage before becoming an API response. As a
/// result, the token counts in `usage` will not match one-to-one with the exact visible
/// content of an API request or response.
///
/// For example, `output_tokens` will be non-zero, even for an empty string response from
/// Claude.
///
/// Total input tokens in a request is the summation of `input_tokens`,
/// `cache_creation_input_tokens`, and `cache_read_input_tokens`.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct Usage {
    /// Breakdown of cached tokens by TTL
    cache_creation: Option<CacheCreation>,

    /// The number of input tokens used to create the cache entry.
    cache_creation_input_tokens: Option<i64>,

    /// The number of input tokens read from the cache.
    cache_read_input_tokens: Option<i64>,

    /// The geographic region where inference was performed for this request.
    inference_geo: Option<String>,

    /// The number of input tokens which were used.
    input_tokens: i64,

    /// The number of output tokens which were used.
    output_tokens: i64,

    /// The number of server tool requests.
    server_tool_use: Option<ServerToolUsage>,

    /// If the request used the priority, standard, or batch tier.
    service_tier: Option<ServiceTier>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct CacheCreation {
    /// The number of input tokens used to create the 1 hour cache entry.
    #[serde(rename = "ephemeral_1h_input_tokens")]
    ephemeral_1_h_input_tokens: i64,

    /// The number of input tokens used to create the 5 minute cache entry.
    #[serde(rename = "ephemeral_5m_input_tokens")]
    ephemeral_5_m_input_tokens: i64,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ServerToolUsage {
    /// The number of web fetch tool requests.
    web_fetch_requests: i64,

    /// The number of web search tool requests.
    web_search_requests: i64,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ListResponseModelInfo {
    data: Vec<ModelInfo>,

    /// First ID in the `data` list. Can be used as the `before_id` for the previous page.
    first_id: Option<String>,

    /// Indicates if there are more results in the requested page direction.
    has_more: bool,

    /// Last ID in the `data` list. Can be used as the `after_id` for the next page.
    last_id: Option<String>,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ModelInfo {
    /// Object mapping capability names to their support details. Keys are always present for all
    /// known capabilities.
    capabilities: Option<ModelCapabilities>,

    /// RFC 3339 datetime string representing the time at which the model was released. May be
    /// set to an epoch value if the release date is unknown.
    created_at: String,

    /// A human-readable name for the model.
    display_name: String,

    /// Unique model identifier.
    id: String,

    /// Maximum input context window size in tokens for this model.
    max_input_tokens: Option<i64>,

    /// Maximum value for the `max_tokens` parameter when using this model.
    max_tokens: Option<i64>,

    /// Object type.
    ///
    /// For Models, this is always `"model"`.
    #[serde(rename = "type")]
    model_info_type: Type,
}

/// Model capability information.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ModelCapabilities {
    /// Whether the model supports the Batch API.
    batch: CapabilitySupport,

    /// Whether the model supports citation generation.
    citations: CapabilitySupport,

    /// Whether the model supports code execution tools.
    code_execution: CapabilitySupport,

    /// Context management support and available strategies.
    context_management: ContextManagementCapability,

    /// Effort (reasoning_effort) support and available levels.
    effort: EffortCapability,

    /// Whether the model accepts image content blocks.
    image_input: CapabilitySupport,

    /// Whether the model accepts PDF content blocks.
    pdf_input: CapabilitySupport,

    /// Whether the model supports structured output / JSON mode / strict tool schemas.
    structured_outputs: CapabilitySupport,

    /// Thinking capability and supported type configurations.
    thinking: ThinkingCapability,
}

/// Whether the model supports the Batch API.
///
/// Indicates whether a capability is supported.
///
/// Whether the model supports citation generation.
///
/// Whether the model supports code execution tools.
///
/// Whether the model supports high effort level.
///
/// Whether the model supports low effort level.
///
/// Whether the model supports max effort level.
///
/// Whether the model supports medium effort level.
///
/// Whether the model accepts image content blocks.
///
/// Whether the model accepts PDF content blocks.
///
/// Whether the model supports structured output / JSON mode / strict tool schemas.
///
/// Whether the model supports thinking with type 'adaptive' (auto).
///
/// Whether the model supports thinking with type 'enabled'.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct CapabilitySupport {
    /// Whether this capability is supported by the model.
    supported: bool,
}

/// Context management support and available strategies.
///
/// Context management capability details.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ContextManagementCapability {
    /// Whether the clear_thinking_20251015 strategy is supported.
    clear_thinking_20251015: Option<CapabilitySupport>,

    /// Whether the clear_tool_uses_20250919 strategy is supported.
    clear_tool_uses_20250919: Option<CapabilitySupport>,

    /// Whether the compact_20260112 strategy is supported.
    compact_20260112: Option<CapabilitySupport>,

    /// Whether this capability is supported by the model.
    supported: bool,
}

/// Effort (reasoning_effort) support and available levels.
///
/// Effort (reasoning_effort) capability details.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct EffortCapability {
    /// Whether the model supports high effort level.
    high: CapabilitySupport,

    /// Whether the model supports low effort level.
    low: CapabilitySupport,

    /// Whether the model supports max effort level.
    max: CapabilitySupport,

    /// Whether the model supports medium effort level.
    medium: CapabilitySupport,

    /// Whether this capability is supported by the model.
    supported: bool,
}

/// Thinking capability and supported type configurations.
///
/// Thinking capability details.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ThinkingCapability {
    /// Whether this capability is supported by the model.
    supported: bool,

    types: ThinkingTypes,
}

/// Supported thinking type configurations.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ThinkingTypes {
    /// Whether the model supports thinking with type 'adaptive' (auto).
    adaptive: CapabilitySupport,

    /// Whether the model supports thinking with type 'enabled'.
    enabled: CapabilitySupport,
}

/// Object type.
///
/// For Models, this is always `"model"`.
#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum Type {
    Model,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErrorResponse {
    error: Error,

    request_id: Option<String>,

    #[serde(rename = "type")]
    error_response_type: ErrorResponseType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
pub struct Error {
    message: String,

    #[serde(rename = "type")]
    error_type: ErrorType,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ErrorType {
    #[serde(rename = "api_error")]
    ApiError,

    #[serde(rename = "authentication_error")]
    AuthenticationError,

    #[serde(rename = "billing_error")]
    BillingError,

    #[serde(rename = "invalid_request_error")]
    InvalidRequestError,

    #[serde(rename = "not_found_error")]
    NotFoundError,

    #[serde(rename = "overloaded_error")]
    OverloadedError,

    #[serde(rename = "permission_error")]
    PermissionError,

    #[serde(rename = "rate_limit_error")]
    RateLimitError,

    #[serde(rename = "timeout_error")]
    TimeoutError,
}

#[derive(Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ErrorResponseType {
    Error,
}
