import { readFileSync, writeFileSync, readdirSync } from "node:fs";

const SCHEMAS_DIR = "generated/schemas";
const OUT_PATH = "rust/src/types.rs";

const FILES = [
  "CreateMessageParams.rs",
  "Message.rs",
  "ListResponse_ModelInfo_.rs",
  "ModelInfo.rs",
  "ErrorResponse.rs",
];

interface ParsedBlock {
  kind: "struct" | "enum" | "type" | "use";
  name: string;
  full: string;
}

function parseBlocks(source: string): ParsedBlock[] {
  const blocks: ParsedBlock[] = [];
  const lines = source.split("\n");
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (line.startsWith("use ")) {
      blocks.push({ kind: "use", name: line, full: line });
      i++;
      continue;
    }

    if (line.startsWith("pub type ")) {
      const match = line.match(/^pub type (\w+)/);
      if (match) {
        blocks.push({ kind: "type", name: match[1], full: line });
      }
      i++;
      continue;
    }

    const structMatch = line.match(/^pub struct (\w+)/);
    const enumMatch = line.match(/^pub enum (\w+)/);

    if (structMatch || enumMatch) {
      const name = (structMatch || enumMatch)![1];
      const kind = structMatch ? "struct" : "enum";

      const docLines: string[] = [];
      let j = i - 1;
      while (j >= 0 && (lines[j].startsWith("///") || lines[j].startsWith("#["))) {
        docLines.unshift(lines[j]);
        j--;
      }

      const bodyLines: string[] = [];
      bodyLines.push(line);
      i++;
      let braceDepth = line.includes("{") ? 1 : 0;
      if (!line.includes("{")) {
        while (i < lines.length) {
          bodyLines.push(lines[i]);
          if (lines[i].includes("{")) {
            braceDepth++;
            i++;
            break;
          }
          i++;
        }
      }

      while (i < lines.length && braceDepth > 0) {
        bodyLines.push(lines[i]);
        for (const ch of lines[i]) {
          if (ch === "{") braceDepth++;
          if (ch === "}") braceDepth--;
        }
        i++;
      }

      const full = [...docLines, ...bodyLines].join("\n");
      blocks.push({ kind, name, full });
      continue;
    }

    i++;
  }

  return blocks;
}

function main() {
  const seen = new Set<string>();
  const uses = new Set<string>();
  const typeBlocks: string[] = [];

  for (const file of FILES) {
    const path = `${SCHEMAS_DIR}/${file}`;
    const source = readFileSync(path, "utf-8");
    const blocks = parseBlocks(source);

    for (const block of blocks) {
      if (block.kind === "use") {
        uses.add(block.full);
        continue;
      }

      if (seen.has(block.name)) continue;
      seen.add(block.name);
      typeBlocks.push(block.full);
    }
  }

  const header = [
    "// Generated by quicktype from the Anthropic OpenAPI spec.",
    "// Do not edit manually — re-run `just generate` instead.",
    "",
    "#![allow(dead_code)]",
    "#![allow(clippy::redundant_field_names)]",
    "",
    ...Array.from(uses).sort(),
    "",
  ];

  const output = [...header, ...typeBlocks.map((b) => `\n${b}`)].join("\n");
  writeFileSync(OUT_PATH, output + "\n");
  console.log(`Wrote ${OUT_PATH} with ${seen.size} type definitions`);
}

main();
